### PR TITLE
Full refactoring of the repository

### LINKED ISSUE #8: Tidying the project structure
After discussing with @sfarrens it appears the current flat structure of the project is driven by the use of `thebe` for the live code within each page. This experimental feature seems to not work well when the book repo is structured with folders (e.g. for chapters).

Since the project is growing, before it becomes not easily manageable, I propose that we momentarily deactivate the live coding feature to tidy the repository content. And then figure out how to make it work with such structure.

Let me know what you think @sfarrens @EiffL

### PR DESCRIPTION
**Pull request by aboucaud**
In this PR I propose a full refactoring of the repository while maintaining all the existing features (live code).
This supersedes #10.

The main changes include: 
- book specific files have been moved to the `shearbook` directory and ordered by parts (each part gets a folder)
- images and bib files are moved to specific directories
- code files are gathered in the `shrbk` folder to make a companion library that can be installed (avoids having to deal with sys.path for the live coding)
- additional files `README.md` and CI scripts have been updated accordingly

Fixes #8

### CODE REVIEW

**Comment by sfarrens** [comment]
Looks good @aboucaud! I will review this PR before next Friday.

**Comment by sfarrens** [comment]
@aboucaud I ran into a couple of issues when testing your PR locally.

- When trying to run the "Live Code" in "Moments Basic" I get the following error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-1292acdfc944> in <module>
      1 # Automatic import for live code
      2 import numpy as np
----> 3 from shrbk.plot import *
      4 from shrbk.data import *

ModuleNotFoundError: No module named 'shrbk'
```

I think that the conda `environment.yml` and/or the `requirements.txt` need to build the library so that Binder can access the modules.

- Also when trying to launch the notebook on Binder I get a "404 : Not Found"  error.  I guess this is expected as the file is not actually hosted on the CosmoStat repo yet, but the link is the following:

https://mybinder.org/v2/gh/CosmoStat/Shear-and-PSF-Reading-Group/develop?urlpath=tree/moments/moments-basic.ipynb

It seems to me there is a missing `shearbook/` before `moments`.

**Comment by aboucaud** [comment]
Okay so everything is normal because Binder only builds from actual published branches, not PRs.
If you want to make it work **for now**, you need to go to `_config.yml` and replace at the bottom the repository url with
`https://github.com/aboucaud/Shear-and-PSF-Reading-Group` and the branch with `refactor-lib`.

Then you clean and rebuild the book and it should work.

The beauty of Binder is that when it finds a `setup.py` it automatically runs it last when building the container.

**Comment by sfarrens** [comment]
OK, cool. Live code seems to work perfectly. The issue with the binder link, however, is still there.

**Comment by sfarrens** [comment]
Note that you should also update [Line 56 in `interact.py`](https://github.com/CosmoStat/Shear-and-PSF-Reading-Group/blob/develop/interact.py#L56) to be consistent with the new file structure.

*e.g.*

```python
url = (f'{binder}{git_repo}/{branch}/?urlpath=tree/shearbook/{file_name}{suffix}')
```

**Comment by aboucaud** [comment]
Right, I was in the middle of making that change when I realised that these interactive notebooks are not part of the book and could totally be placed in a separate `notebooks` folder in the root directory.

```bash
├── environment.yml
├── LICENSE
├── README.md
├── requirements.txt
├── setup.py
├── notebooks
├── shearbook
└── shrbk
```

What do you think ?

**Comment by sfarrens** [comment]
Yeah, that might be a good way to avoid confusion. Do you want to keep the exclusion pattern for `*_interact*` in the `_config. yml`?

**Comment by aboucaud** [comment]
I removed it altogether.

**Review by sfarrens — APPROVED** [review]

**Comment by sfarrens** [comment]
@aboucaud Looks good to me. 

Is the "Launch Binder" (under the rocket) button working for you locally?

My Atom had a bit of a fit and somehow managed to push some commits to the develop branch of this repo rather than my fork. This has created a conflict. I will try to sort it out, sorry!

**Comment by aboucaud** [comment]
With this latest addition, the binder path should be complete and working.

**Review by sfarrens — APPROVED** [review]

**Comment by sfarrens** [comment]
Cool! I will just sort out this conflict I created and then merge this PR.

**Review by sfarrens — APPROVED** [review]

**Comment by sfarrens** [comment]
Shall I merge or are you planning any further commits?

**Comment by aboucaud** [comment]
Hmmm that might be enough 😄

**Pull request merged**
